-- 테이블 삭제
DROP TABLE "TB_REPORT";
DROP TABLE "TB_INQUIRY";
DROP TABLE "TB_NOTICE";
DROP TABLE "TB_EVENT_COMMENT";
DROP TABLE "TB_EVENT";


-- 시퀀스 삭제
DROP SEQUENCE "EVENT_NO";
DROP SEQUENCE "INQ_NO";
DROP SEQUENCE "NOTICE_NO";
DROP SEQUENCE "REP_NO";
DROP SEQUENCE "EVENT_COM_NO";

-- 시퀀스 생성
CREATE SEQUENCE "REP_NO";
CREATE SEQUENCE "INQ_NO";
CREATE SEQUENCE "NOTICE_NO";
CREATE SEQUENCE "EVENT_NO";
CREATE SEQUENCE "EVENT_COM_NO";

-- TB_REPORT 생성
CREATE TABLE "TB_REPORT" (
	"REP_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NOT NULL,
	"REP_CONTENTS"	VARCHAR2(2000)		NOT NULL,
	"REP_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"REP_CLSFC"	VARCHAR2(20)		NOT NULL,
	"REP_PROCESSING"	CHAR(1)	DEFAULT 'N' CHECK(REP_PROCESSING IN('Y','N')) NOT NULL,
	"REP_STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "TB_REPORT"."REP_NO" IS '신고번호';

COMMENT ON COLUMN "TB_REPORT"."MEM_NO" IS '회원번호';

COMMENT ON COLUMN "TB_REPORT"."REP_CONTENTS" IS '내용';

COMMENT ON COLUMN "TB_REPORT"."REP_DATE" IS '작성일';

COMMENT ON COLUMN "TB_REPORT"."REP_CLSFC" IS '분류';

COMMENT ON COLUMN "TB_REPORT"."REP_PROCESSING" IS '처리여부';

COMMENT ON COLUMN "TB_REPORT"."REP_STATUS" IS '상태';

ALTER TABLE "TB_REPORT" ADD CONSTRAINT "PK_TB_REPORT" PRIMARY KEY (
	"REP_NO"
);

ALTER TABLE "TB_REPORT" ADD CONSTRAINT "FK_REPORT_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "TB_MEMBER" (
	"MEM_NO"
)
ON DELETE CASCADE;

-- TB_INQUIRY

CREATE TABLE "TB_INQUIRY" (
	"INQ_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NOT NULL,
	"INQ_NAME"	VARCHAR2(2000)		NOT NULL,
	"INQ_QUESTION"	VARCHAR2(2000)		NOT NULL,
	"INQ_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"INQ_ANSWER"	VARCHAR2(2000)		NULL,
	"INQ_PROCESSING"	CHAR(1)	DEFAULT 'N' CHECK(INQ_PROCESSING IN('Y','N'))	NOT NULL,
	"INQ_PRIVATE"	CHAR(1)	DEFAULT 'Y' CHECK(INQ_PRIVATE IN('Y','N'))	NOT NULL,
	"INQ_STATUS"	CHAR(1)	DEFAULT 'Y'	CHECK(INQ_STATUS IN('Y','N')) NOT NULL
);

COMMENT ON COLUMN "TB_INQUIRY"."INQ_NO" IS '문의번호';

COMMENT ON COLUMN "TB_INQUIRY"."MEM_NO" IS '회원번호';

COMMENT ON COLUMN "TB_INQUIRY"."INQ_NAME" IS '제목';

COMMENT ON COLUMN "TB_INQUIRY"."INQ_QUESTION" IS '질문내용';

COMMENT ON COLUMN "TB_INQUIRY"."INQ_DATE" IS '작성일';

COMMENT ON COLUMN "TB_INQUIRY"."INQ_ANSWER" IS '답변내용';

COMMENT ON COLUMN "TB_INQUIRY"."INQ_PROCESSING" IS '답변여부';

COMMENT ON COLUMN "TB_INQUIRY"."INQ_PRIVATE" IS '공개여부';

COMMENT ON COLUMN "TB_INQUIRY"."INQ_STATUS" IS '상태';

ALTER TABLE "TB_INQUIRY" ADD CONSTRAINT "PK_TB_INQUIRY" PRIMARY KEY (
	"INQ_NO"
);

ALTER TABLE "TB_INQUIRY" ADD CONSTRAINT "FK_INQUIRY_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "TB_MEMBER" (
	"MEM_NO"
)
ON DELETE CASCADE;

-- TB_NOTICE

CREATE TABLE "TB_NOTICE" (
	"NOTICE_NO"	NUMBER		NOT NULL,
	"NOTICE_NAME"	VARCHAR2(100)		NOT NULL,
	"NOTICE_CONTENTS"	VARCHAR2(2000)		NOT NULL,
	"NOTICE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"NOTICE_CLSFC"	VARCHAR2(20)		NOT NULL,
	"NOTICE_STATUS"	CHAR(1)	DEFAULT 'Y' CHECK(NOTICE_STATUS IN('Y','N'))	NOT NULL
);

COMMENT ON COLUMN "TB_NOTICE"."NOTICE_NO" IS '공지번호';

COMMENT ON COLUMN "TB_NOTICE"."NOTICE_NAME" IS '글제목';

COMMENT ON COLUMN "TB_NOTICE"."NOTICE_CONTENTS" IS '내용';

COMMENT ON COLUMN "TB_NOTICE"."NOTICE_DATE" IS '작성일';

COMMENT ON COLUMN "TB_NOTICE"."NOTICE_CLSFC" IS '분류';

COMMENT ON COLUMN "TB_NOTICE"."NOTICE_STATUS" IS '상태';

ALTER TABLE "TB_NOTICE" ADD CONSTRAINT "PK_TB_NOTICE" PRIMARY KEY (
	"NOTICE_NO"
);

-- TB_EVENT 생성

CREATE TABLE "TB_EVENT" (
	"EVENT_NO"	NUMBER		NOT NULL,
	"EVENT_NAME"	VARCHAR2(100)		NOT NULL,
	"EVENT_CONTENTS"	VARCHAR2(2000)		NOT NULL,
	"EVENT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"EVENT_PROCESSING"	CHAR(1)	DEFAULT 'Y' CHECK(EVENT_PROCESSING IN('Y','N'))	NOT NULL,
	"EVENT_STATUS"	CHAR(1)	DEFAULT 'Y' CHECK(EVENT_STATUS IN('Y','N'))	NOT NULL
);

COMMENT ON COLUMN "TB_EVENT"."EVENT_NO" IS '이벤트번호';

COMMENT ON COLUMN "TB_EVENT"."EVENT_NAME" IS '이벤트 제목';

COMMENT ON COLUMN "TB_EVENT"."EVENT_CONTENTS" IS '이벤트 내용';

COMMENT ON COLUMN "TB_EVENT"."EVENT_DATE" IS '작성일';

COMMENT ON COLUMN "TB_EVENT"."EVENT_PROCESSING" IS '진행여부';

COMMENT ON COLUMN "TB_EVENT"."EVENT_STATUS" IS '상태';

ALTER TABLE "TB_EVENT" ADD CONSTRAINT "PK_TB_EVENT" PRIMARY KEY (
	"EVENT_NO"
);

-- TB_EVENT_COMMENT

CREATE TABLE "TB_EVENT_COMMENT" (
	"EVENT_COM_NO"	NUMBER		NOT NULL,
	"EVENT_NO"	NUMBER		NOT NULL,
	"MEM_NO"	NUMBER		NOT NULL,
	"EVENT_COM_CONTENTS"	VARCHAR2(300)		NOT NULL,
	"EVENT_COM_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"EVENT_COM_STATUS"	CHAR(1)	DEFAULT 'Y' CHECK(EVENT_COM_STATUS IN('Y','N'))	NOT NULL
);

COMMENT ON COLUMN "TB_EVENT_COMMENT"."EVENT_COM_NO" IS '이벤트댓글번호';

COMMENT ON COLUMN "TB_EVENT_COMMENT"."EVENT_NO" IS '이벤트번호';

COMMENT ON COLUMN "TB_EVENT_COMMENT"."MEM_NO" IS '회원번호';

COMMENT ON COLUMN "TB_EVENT_COMMENT"."EVENT_COM_CONTENTS" IS '이벤트댓글내용';

COMMENT ON COLUMN "TB_EVENT_COMMENT"."EVENT_COM_DATE" IS '이벤트댓글작성일';

COMMENT ON COLUMN "TB_EVENT_COMMENT"."EVENT_COM_STATUS" IS '상태';

ALTER TABLE "TB_EVENT_COMMENT" ADD CONSTRAINT "PK_EVENT_COMMENT_1" PRIMARY KEY (
	"EVENT_COM_NO"
);

ALTER TABLE "TB_EVENT_COMMENT" ADD CONSTRAINT "FK_EVENT_COMMENT_2" FOREIGN KEY (
	"EVENT_NO"
)
REFERENCES "TB_EVENT" (
	"EVENT_NO"
)
ON DELETE CASCADE;

ALTER TABLE "TB_EVENT_COMMENT" ADD CONSTRAINT "FK_EVENT_COMMENT_1" FOREIGN KEY (
	"MEM_NO"
)
REFERENCES "TB_MEMBER" (
	"MEM_NO"
)
ON DELETE CASCADE;


-- INSERT문
-- TB_REPORT

INSERT INTO TB_REPORT(
REP_NO,
MEM_NO,
REP_CONTENTS,
REP_DATE,
REP_CLSFC,
REP_PROCESSING,
REP_STATUS
)
VALUES (
REP_NO.NEXTVAL,
1,
'의미없는 게시글 신고합니다 www.todaytable.com/~~~',
SYSDATE,
'게시글신고',
DEFAULT,
DEFAULT
);

INSERT INTO TB_REPORT(
REP_NO,
MEM_NO,
REP_CONTENTS,
REP_DATE,
REP_CLSFC,
REP_PROCESSING,
REP_STATUS
)
VALUES (
REP_NO.NEXTVAL,
1,
'비매너 댓글 신고합니다 www.todaytable.com/~~~',
SYSDATE,
'댓글신고',
'Y',
DEFAULT
);

INSERT INTO TB_REPORT(
REP_NO,
MEM_NO,
REP_CONTENTS,
REP_DATE,
REP_CLSFC,
REP_PROCESSING,
REP_STATUS
)
VALUES (
REP_NO.NEXTVAL,
3,
'욕설 댓글 신고합니다 www.todaytable.com/~~~',
SYSDATE,
'댓글신고',
DEFAULT,
DEFAULT
);

INSERT INTO TB_REPORT(
REP_NO,
MEM_NO,
REP_CONTENTS,
REP_DATE,
REP_CLSFC,
REP_PROCESSING,
REP_STATUS
)
VALUES (
REP_NO.NEXTVAL,
4,
'비매너 게시글 신고합니다 www.todaytable.com/~~~',
SYSDATE,
'게시글신고',
DEFAULT,
DEFAULT
);

INSERT INTO TB_REPORT(
REP_NO,
MEM_NO,
REP_CONTENTS,
REP_DATE,
REP_CLSFC,
REP_PROCESSING,
REP_STATUS
)
VALUES (
REP_NO.NEXTVAL,
1,
'게시글 신고접수 www.todaytable.com/~~~',
SYSDATE,
'게시글신고',
DEFAULT,
DEFAULT
);

-- TB_INQUIRY

INSERT INTO TB_INQUIRY(
INQ_NO,
MEM_NO,
INQ_NAME,
INQ_QUESTION,
INQ_DATE,
INQ_ANSWER,
INQ_PROCESSING,
INQ_PRIVATE,
INQ_STATUS
)
VALUES (
INQ_NO.NEXTVAL,
1,
'레시피 조회 화면이 안나와요',
'원래 잘 됐는데 컴퓨터 바꾸고 나서 레시피 조회가 안되네요 답변부탁드립니다.',
SYSDATE,
'안녕하세요 오늘의 식탁입니다. 문의주신 내용 답변드리겠습니다.
조회가 안된다면 chrome 브라우저를 사용해보세요',
'Y',
DEFAULT,
DEFAULT
);

INSERT INTO TB_INQUIRY(
INQ_NO,
MEM_NO,
INQ_NAME,
INQ_QUESTION,
INQ_DATE,
INQ_ANSWER,
INQ_PROCESSING,
INQ_PRIVATE,
INQ_STATUS
)
VALUES (
INQ_NO.NEXTVAL,
1,
'레시피를 보니까 배고파요',
'레시피를 보니까 배고프네요 ㅡㅡ;;',
SYSDATE,
NULL,
DEFAULT,
'Y',
DEFAULT
);

INSERT INTO TB_INQUIRY(
INQ_NO,
MEM_NO,
INQ_NAME,
INQ_QUESTION,
INQ_DATE,
INQ_ANSWER,
INQ_PROCESSING,
INQ_PRIVATE,
INQ_STATUS
)
VALUES (
INQ_NO.NEXTVAL,
1,
'가지고 있는 레시피를 공유하려합니다.',
'제가 가지고 있는 비밀 레시피를 공유하려고합니다',
SYSDATE,
'안녕하세요 오늘의 식탁입니다.
레시피 작성을 이용해 공유해주세요',
'Y',
'Y',
DEFAULT
);

INSERT INTO TB_INQUIRY(
INQ_NO,
MEM_NO,
INQ_NAME,
INQ_QUESTION,
INQ_DATE,
INQ_ANSWER,
INQ_PROCESSING,
INQ_PRIVATE,
INQ_STATUS
)
VALUES (
INQ_NO.NEXTVAL,
3,
'레시피 등록이 안돼요',
'레시피 등록이 안되네요 ;;;;',
SYSDATE,
'안녕하세요 오늘의 식탁입니다.
다시한번 시도해보세요',
'Y',
DEFAULT,
DEFAULT
);

INSERT INTO TB_INQUIRY(
INQ_NO,
MEM_NO,
INQ_NAME,
INQ_QUESTION,
INQ_DATE,
INQ_ANSWER,
INQ_PROCESSING,
INQ_PRIVATE,
INQ_STATUS
)
VALUES (
INQ_NO.NEXTVAL,
5,
'분류별 레시피에서 404에러가 떠요',
'분류별 레시피에서 에러뜹니다 조치해주세여',
SYSDATE,
'안녕하세요 오늘의 식탁입니다.
현재 잘 됩니다.',
'Y',
DEFAULT,
DEFAULT
);

-- TB_NOTICE

INSERT INTO TB_NOTICE(
NOTICE_NO,
NOTICE_NAME,
NOTICE_CONTENTS,
NOTICE_DATE,
NOTICE_CLSFC,
NOTICE_STATUS)
VALUES (
NOTICE_NO.NEXTVAL,
'2020년 부터 익스플로에서는 동영상이 나오지 않습니다',
'2020년 말부터 공식적으로 Adobe사의 플래시 플레이어 지원이 중단됨에 따라 
플래시 플레이어를 통한 동영상 재생이 불가합니다
동영상이 나오는 브라우저로 업그레이드 하시기 바랍니다',
SYSDATE,
'일반',
DEFAULT
);

INSERT INTO TB_NOTICE(
NOTICE_NO,
NOTICE_NAME,
NOTICE_CONTENTS,
NOTICE_DATE,
NOTICE_CLSFC,
NOTICE_STATUS)
VALUES (
NOTICE_NO.NEXTVAL,
'금일 8월 16일 업데이트가 있습니다',
'금일 서버 업데이트가 있어 서버접속과 기타 기능이 작동하지 않을수가 있습니니다 조속히 마치도록 하겠습니다
금일 작업은 8월 16일 저녁쯤에 끝날예정입니다
혹시 작동이 안되는 기능이 있으면 1:1 문의 게시판에 바로 부탁드립니다',
SYSDATE,
'긴급',
DEFAULT
);



